[package]
name = "grepolis_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
eframe = "0.22.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
tokio = {version = "1.28.2", features=["sync"]}
