[package]
name = "turunmap"
version = "1.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = { version = "0.22", features = ["serde", "persistence"]}
eframe = { version = "0.22", features = ["persistence"]}
egui_extras = "0.22"
reqwest = { version = "0.11.18", features=["gzip", "deflate", "blocking"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
form_urlencoded = "1.1.0"
uuid = { version = "1.3.3", features=["v4", "fast-rng", "serde"] }
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
anyhow = "1.0.71"
directories-next = "2.0.0"
time = { version="0.3.23", features=["formatting", "parsing", "local-offset", "macros"] }
sha2 = "0.10.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
codegen-units = 1
debug = false
lto = true
incremental = false
opt-level = 3
overflow-checks = false
strip = "debuginfo"