[package]
name = "grepolis_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
eframe = "0.22.0"
rand = "0.8.5"
reqwest = {version = "0.11.18", features=["gzip", "deflate"]}
rusqlite = { version = "0.29.0", features = ["bundled"] }
futures = "0.3.28"
tokio = {version = "1.28.2", features=["rt-multi-thread"]}
form_urlencoded = "1.1.0"