# from https://github.com/rust-build/rust-build.action
# and https://github.com/BamPeers/rust-ci-github-actions-workflow/blob/main/.github/workflows/release-packaging.yaml
# and https://trstringer.com/github-actions-create-release-upload-artifacts/

# Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Rust Release Build & Draft

on:
  # draft a release when pushing a tag
  push:
    tags:
      - "*"

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Draft Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Compile for Windows
        id: build_artifact_win
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none

      # - name: Compile for Linux
      #   id: build_artifact_linux
      #   uses: rust-build/rust-build.action@v1.4.3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     RUSTTARGET: x86_64-unknown-linux-musl
      #     UPLOAD_MODE: none

      # - name: Compile for Apple
      #   id: build_artifact_apple
      #   uses: rust-build/rust-build.action@v1.4.3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     RUSTTARGET: x86_64-apple-darwin
      #     UPLOAD_MODE: none

      - name: Upload artifact to release
        id: upload_artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: TurunMap-${{ steps.build_artifact_win.target }}-${{ github.ref }}
          asset_path: ${{ steps.build_artifact_win.outputs.BUILT_ARCHIVE }}
          asset_content_type: application/zip
